### ISSUE TITLE
[BUG] Playwright seems to be slow when using Java on a MacBook M1 Max

### ISSUE THREAD

**Issue by roydekleijn** [microsoft/playwright-java#1254] opened 2023-03-29 18:16 UTC
### System info
- Playwright Version: v1.31.0
- Operating System: [macOS Venture 13.2.1]
- Browser: [All, but Edge is extremely slow]
- Other info:
roy@testsmith playwright % java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

mvn version 3.9.1

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/roydekleijn/playwright-java-slow-on-mac

**Steps**
`mvn clean test` will execute the same test twice.

**Expected**
I expect it to be as fast as (or close to) Playwright using JS/TS.

**Actual**
It is much slower. Even the browser startup takes a decent amount of time. I see timings of:
23104
14800
17969
14543

The JS/TS implementation gives:
1369
1005
1114
1003
1127

Both tests are executed in headed mode.

**Comment by yury-s** [comment] 2023-03-29 22:24
I can confirm that there is 3x difference when running with MS Edge (~5s in node.js vs ~15s in java). Edge runs in `arm64` mode under nodejs and in `x86_64 translated` under java (even thought it is the same universal binary). I couldn't see the difference with bundled Chromium as we download aarch64 rather than universal browser binaries.

**Comment by yury-s** [comment] 2023-03-29 22:28
This will be resolved automatically once we address https://github.com/microsoft/playwright-java/issues/1198 and include aarm64 build of Node.js.

**Comment by roydekleijn** [comment] 2023-03-29 22:34
awesome, thanks for your quick response, and great to see that's already taken care of.

**Comment by yury-s** [comment] 2023-03-30 01:20
With the fix merged it should be working now. It is scheduled for 1.33. Note that you also need to make sure that the test is running in a native arm64 jvm to not trigger Rosetta mode for universal browser binaries.

**Comment by yury-s** [comment] 2023-04-04 18:02
It's at least two weeks from now.

**Comment by roydekleijn** [comment] 2023-05-02 21:52
I tried V1.33, but it is still slow on Edge...

**Comment by yury-s** [comment] 2023-05-02 22:52
Make sure your JVM supports Apple Silicon. Can you run the following command line and go to `chrome://version` in the browser:

```sh
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="cr --channel msedge"
```
First line should be something like `Microsoft Edge  112.0.1722.68 (Official build) (arm64)`


`

**Comment by roydekleijn** [comment] 2023-05-05 13:51
113.0.5672.53 (Developer Build) (arm64)

**Comment by mxschmitt** [comment] 2023-05-06 09:05
We always install Microsoft Edge universal binaries, so my guess is that your terminal is a rosetta emulated one. It installs the right Edge but starts in x86_64 emulated mode. I'm unfortunately not able to test it, since I haven't enabled the rosetta mode on my system.

**Comment by yury-s** [comment] 2023-05-09 16:14
@roydekleijn what do the following two commands print for you in the terminal where you start playwright?

```sh
arch
file $(which java)
```

**Comment by yury-s** [comment] 2023-05-22 17:00
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-05-22 17:00 UTC
Labels: triaging

**Comment by roydekleijn** [comment] 2023-05-22 19:42
I reinstalled Microsoft Edge (Apple Chip), and I use v1.33. Now the timings are:
6306
2418
2608
2619
2611
2620
2027
2086
2086
2115
2096
2054

Much better.. Unfortunately not sure what the root cause was.
