### ISSUE TITLE
[Question]How can I get a clear context ？

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#614] opened 2021-09-20 05:36 UTC
Hello,
How can I get a clear context not reopen context ? Delete cookies localstorage...

**Comment by yury-s** [comment] 2021-09-20 18:04
Please create issue with the same question only in one of the repos. Closing this as duplicate of https://github.com/microsoft/playwright/issues/9013

**Closed by yury-s** 2021-09-20 18:04 UTC
