### ISSUE TITLE
change browser "platform" [Question]: 

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#569] opened 2021-08-16 00:26 UTC
### Your question

Hello,
Could you tell how to change browser "platform"? I don't mean to change UA ，changes "platform" windows to linux.
Thanks

**Comment by mxschmitt** [comment] 2021-08-16 09:25
Seems like a duplicate of https://github.com/microsoft/playwright/issues/8216 to me. Currently its not yet possible.

**Comment by pavelfeldman** [comment] 2021-08-17 00:35
What is your use case?

**Comment by xiaowenhuman** [comment] 2021-08-17 05:31
I just want to crawl some data, some of my other businesses also use it.

**Comment by yury-s** [comment] 2021-08-18 16:16
Closing in favor of the upstream issue as it'd have to be implemented upstream first. Please upvote [that issue](https://github.com/microsoft/playwright/issues/8216) if you need the feature.

**Closed by yury-s** 2021-08-18 16:16 UTC
Labels: triaging
