### ISSUE TITLE
[Question] Simulated multithreading

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright-java#411] opened 2021-04-24 03:22 UTC
Hello,
<img width="819" alt="截屏2021-04-24 上午11 19 58" src="https://user-images.githubusercontent.com/1261933/115945594-08666780-a4ef-11eb-8d45-94e3a6de190b.png">

Playwright is a no thead safe framework.
I  can simulate multithreading in Python solve thread safety.How do I do that in Java？
.

**Comment by yury-s** [comment] 2021-04-25 02:10
As mentioned [here](https://github.com/microsoft/playwright-java#is-playwright-thread-safe) Playwright is not thread-safe. You can create multiple instances on different threads in one process but you need to make sure that each instance and its objects are accessed only on the thread where they are created. What do you want to parallelize?

**Comment by yury-s** [comment] 2021-04-27 18:14
Closing per my response above. Please reopen if you have further questions.

**Closed by yury-s** 2021-04-27 18:14 UTC

**Comment by spegoraro** [comment] 2021-08-30 04:23
This is a significant limitation compared to the other implementations. Would you consider adding callbacks or some other asynchronicity to the existing method calls? At least that way callers can run operations in multiple pages simultaneously and process the results as they arrive.

**Comment by yury-s** [comment] 2021-08-30 16:29
There are no such plan, the java API is synchronous by design. Unless Java support JS-style promises we don't want to change this. Note that even in Node.js we don't recommend using multiple context in single browser for parallelization, instead separate browser is launched per test worker. Can you share more details about where current sync api is limiting and why launching playwrights on parallel threads is not an option for you?

**Comment by spegoraro** [comment] 2021-08-31 00:22
We're using browser automation for a scraping scenario rather than testing. We have a queue of operations to be processed concurrently. While we could start one playwright instance per job, its startup time dominates the overall execution time of a job. To get around this we can use a pool of instances but I was hoping to avoid this, hence my question.

I wasn't aware of the recommendation against multiple contexts per instance. Can you send me a link to it in the docs please?

**Comment by yury-s** [comment] 2021-08-31 01:07
> I wasn't aware of the recommendation against multiple contexts per instance. Can you send me a link to it in the docs please?

I didn't say that, multiple context are recommended to be used for [state isolation](https://playwright.dev/java/docs/core-concepts/#browser-contexts) between different test scenarios. Even though you may try to increase parallelism by running multiple contexts/pages in the same browser the recommended way for running tests in parallel is to launch separate browsers and withing them use contexts for isolation between tests. This is what we do in playwright test runner in node.js as well. Having said that, scraping scenarios have different trade-offs and you may well choose to open multiple contexts/pages concurrently. This would certainly be more difficult in java due to the synchronous nature of the API.

**Comment by spegoraro** [comment] 2021-08-31 01:09
No problem, I'll play with using a pool of instances first to see what the performance is like, if it isn't adequate then I'll re-implement it with the Node.js api instead. Thanks for the awesome work!
