### ISSUE TITLE
[BUG] getByText() does not resolve "double quotes" as character

### ISSUE THREAD

**Issue by RafikBELAZOUZ** [microsoft/playwright-java#1440] opened 2023-12-13 10:40 UTC
I need to assert the presence of a String using page.getByText(), that String that is returned from parsing a CSV file.
It contains a double quote " which is correctly escaped in the CSV ("") and is correctly sent to getByText()
However, it doesn't seem to resolve it, it automatically converts the String to a Regex and I have this error: 

```
com.microsoft.playwright.PlaywrightException: Error {
  message='SyntaxError: Invalid flags supplied to RegExp constructor 'i >> nth=-1'
```

Though it only does that when i run .last(), if I do not it just doesnt find the element

### Simplified Source code to reproduce 
Just run: 

```java
page.getByText("\"").last();
```

### System info
- Playwright Version: [v1.37]
- Operating System: [All]
- Browser: [Chromium]

**Actual**

I could make it work using the legacy text locator page.locator("text=somethingWithDoubleQuotes")

**Comment by yury-s** [comment] 2023-12-13 18:57
I cannot reproduce it with 1.40, the following exaple works fine:

```java
  @Test
  void shouldCheckTheBox() {
    page.setContent("<input id='checkbox' type='checkbox'>\"</input>");
    page.getByText("\"").click();
  }
```

**Comment by yury-s** [comment] 2023-12-21 03:27
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-12-21 03:27 UTC
Labels: triaging
