### ISSUE TITLE
[Question] get a OutOfMemoryError Exception

### ISSUE THREAD

**Issue by polarbear007** [microsoft/playwright-java#1087] opened 2022-09-28 10:03 UTC
```jxs
public class HelloWorldTest {
	public static void main(String[] args) {
		try (Playwright playwright = Playwright.create()) {
			Browser browser = playwright.chromium().launch();
			Page page = browser.newPage();
			page.navigate("http://playwright.dev");
			System.out.println(page.title());
		}
	}
}
```

Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:140)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:125)

**Comment by yury-s** [comment] 2022-09-28 16:33
Looks like you don't have enough RAM on the machine to run Playwright. What hardware do you use?

**Comment by polarbear007** [comment] 2022-09-29 04:57
system: windows 10
RAM: 8G

**Comment by yury-s** [comment] 2022-09-29 15:55
This looks more than enough, definitely more than the GitHub [Actions VMs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) we run our tests on (without any issues). Perhaps your machine is under memory pressure, check out how much free memory it has before launching playwright / try running the same code on a different machine to see that it works.

If you still deem there's a problem on playwright side we'll need a reproducible example to take an action on that. I'm closing this issue as it is not actionable on our end. Feel free to file a new one with a repro.

**Closed by yury-s** 2022-09-29 15:55 UTC
Labels: triaging
