### ISSUE TITLE
[BUG] 'PlaywrightException: Error: Navigation failed because page crashed!' on Linux

### ISSUE THREAD

**Issue by vadimv** [microsoft/playwright-java#332] opened 2021-03-07 07:59 UTC
OS: Ubuntu 20.04 LTS on WSL, Debian GNU/Linux 10 on WSL after adding required dependencies
Playwright Java:  0.180.0, 1.9.0-alpha-0
This issue is not observed on Windows 10.

```
        final Playwright playwright = Playwright.create();
        final List<BrowserType> browserTypes = Arrays.asList(
                playwright.chromium()
        );

        for (final BrowserType browserType : browserTypes) {
            final Browser browser = browserType.launch();
            final BrowserContext context = browser.newContext();
            final Page page = context.newPage();

            page.navigate("http://playwright.dev");
        }
        playwright.close();
```
Error log 1.9.0-alpha-0:

```
[ERROR] 2021-03-07T08:35:31.695Z pw:api navigating to "http://playwright.dev", waiting until "load"
[ERROR] 2021-03-07T08:35:32.264Z pw:api   navigated to "https://playwright.dev/"
[ERROR] 2021-03-07T08:35:32.644Z pw:api   "domcontentloaded" event fired
2021-03-07T08:35:30.714Z pw:api => BrowserType.launch started
2021-03-07T08:35:31.545Z pw:api <= BrowserType.launch succeeded
2021-03-07T08:35:31.547Z pw:api => Browser.newContext started
2021-03-07T08:35:31.565Z pw:api <= Browser.newContext succeeded
2021-03-07T08:35:31.566Z pw:api => BrowserContext.newPage started
2021-03-07T08:35:31.690Z pw:api <= BrowserContext.newPage succeeded
2021-03-07T08:35:31.691Z pw:api => Page.navigate started
2021-03-07T08:35:40.108Z pw:api <= Page.navigate failed
[ERROR] com.microsoft.playwright.PlaywrightException:
Error {
  message='Navigation failed because page crashed!
=========================== logs ===========================
navigating to "http://playwright.dev", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
  name='Error
  stack='Error: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "http://playwright.dev", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
    at /tmp/playwright-java-6854617622148487159/package/lib/server/frames.js:414:64

```

**Comment by yury-s** [comment] 2021-03-08 19:30
It may be the same root cause as in https://github.com/microsoft/playwright/issues/5687. Does it happen only with Chromium?

I cannot reproduce it on my Ubuntu 20.04 box, will try on WSL when I have access to it. @vadimv could you try launching with the following environment variable `DEBUG=pw:protocol,pw:browser` and send us logs?

**Comment by vadimv** [comment] 2021-03-09 01:36
On Firefox fails after adding a dependency. 
[playwright-firefox.log](https://github.com/microsoft/playwright-java/files/6105187/playwright-firefox.log)

On Chromium after system packages upgrade on Ubuntu seems to have a different stack trace, see logs 1 and 2.

[playwright-chromium-1.log](https://github.com/microsoft/playwright-java/files/6105144/playwright-chromium-1.log)

[playwright-chromium-2.log](https://github.com/microsoft/playwright-java/files/6105154/playwright-chromium-2.log)

**Comment by yury-s** [comment] 2021-03-09 02:24
It looks like there is an issue with establishing IPC connection between browser processes in both cases which lead to browser crashes:

these lines in firefox:
```
[ERROR] 2021-03-09T01:31:55.286Z pw:browser [err] Exiting due to channel error.
[ERROR] 2021-03-09T01:31:55.287Z pw:browser [err] 
[ERROR] 2021-03-09T01:31:55.287Z pw:browser [err] ###!!! [Parent][MessageChannel] Error: (msgtype=0x3A003A,name=PContent::Msg_UpdateSharedData) Channel error: cannot send/recv
```

and these in chromium:
```
[ERROR] 2021-03-09T00:18:08.555Z pw:browser [err] [0309/011804.777632:FATAL:platform_shared_memory_region_posix.cc(100)] Check failed: CheckPlatformHandlePermissionsCorrespondToMode(handle.get(), mode, size). 
```

Both of them have something to do with the shared memory permissions. It's hard to tell more without demangling the stack traces. Is there anything special about your wsl2 configuration and shared memory?

**Comment by yury-s** [comment] 2021-03-09 20:47
Is there a reason you prefer WSL2 Debian over Ubuntu? We test our builds on Ubuntu and it's likely more hassle to maintain browser dependencies up to date on Debian so I'm curious why you'd pick one over the other.

Closing this issue as you seem to have resolved the problem, please reopen if there is anything else we could help with.

**Closed by yury-s** 2021-03-09 20:47 UTC

**Comment by vadimv** [comment] 2021-03-12 18:05
'likely more hassle to maintain browser dependencies up to date on Debian' -- yes, especially for WebKit in my experience. After few attempts I switched to WSL2 Ubuntu. Thanks!
