### ISSUE TITLE
[BUG] Special French characters in HTML elements break Playwright

### ISSUE THREAD

**Issue by DivyaWal7** [microsoft/playwright-java#1341] opened 2023-07-24 07:28 UTC
`<!--` ⚠️⚠️ Do not delete this template ⚠️⚠️ -->

System info
Playwright Version: [v1.30]
Operating System: [All, Windows 11, macOS 13.2, etc.]
Browser: [Chromium]
Other info:
Source code
 I provided exact source code that allows reproducing the issue locally.
Link to the GitHub repository with the repro

[https://github.com/your_profile/playwright_issue_title]

or

Config file

Library used for Playwright Object
```java
import com.microsoft.playwright.Playwright;
``` 

In code below : playwrightObjects is a class which contains Playwright object
```java
Page page = playwrightObjects.getPage();
```

Here addInitScript is a function of playwright that uses the JSON file to merge values in the document
```java
page.addInitScript(Paths.get(<JSON File Path>));
```

Below code specifies the addInitScript function of Playwright

```java
@Override
  public void addInitScript(Path path) {
    withLogging("Page.addInitScript", () -> {
      try {
        byte[] bytes = readAllBytes(path);
        addInitScriptImpl(new String(bytes, UTF_8));
      } catch (IOException e) {
        throw new PlaywrightException("Failed to read script from file", e);
      }
    });
```
 
Below code specifies the addInitScriptImpl function of Playwright
```java
 private void addInitScriptImpl(String script) {
    JsonObject params = new JsonObject();
    params.addProperty("source", script);
    sendMessage("addInitScript", params);
  }
  ```
 
Sample JSON file used
```java {
 
 "Success_x0020_Factors": "<div class=\"ExternalClass4EC3B32FDF9E4AFD95F5327AD74B57B7\"><p><u>L’entente prévoit aussi un paiement forfaitaire unique de 2500&#160;$ ouvrant droit à pension qui représente 3,6&#160;% de plus du salaire du membre moyen.</u></p><p>TEST Dans son propre communiqué, l’Agence du revenu du Canada déclare qu’avec le syndicat, elle a conclu une entente de principe sur le télétravail en dehors de la convention collective. Les deux parties entreprendront un examen de la directive sur les modalités de travail virtuel et vont créer un comité-conseil qui abordera les préoccupations des employés</p></div>",
  "Title": "Test PPB 1"
 }
 ```

Expected
Playwight should provide support for french characters.`

Actual

Special characters in French, such as è, é, è, ê, à, â, ë, ï, î, ô, û, ç, œ, ù, ÿ and >> are not recognized by Playwright.
It break the Playwright parser and make these elements on the page not accessible.
We do not get any exception here but the file that comes here is blank i.e without merging the JSON values.

Please Note : This issue is affecting the functionality, so it would be greatly appreciated if we could resolve it as soon as possible. We are expecting to close this issue by 3rd July considering the criticality of it.

**Comment by DivyaWal7** [comment] 2023-07-24 07:29
Linked issue : https://github.com/microsoft/playwright-java/issues/1328

**Comment by mxschmitt** [comment] 2023-07-26 13:55
Unfortunately I have to close this one again since there was no minimal reproducible attached. We need a script / Java file which we can run locally. See here how to create one: https://stackoverflow.com/help/minimal-reproducible-example

Ideally by following our [getting started](https://playwright.dev/java/docs/intro) and then do something / have steps which produces actual/expected outcomes.

Thanks for your understanding.

**Closed by mxschmitt** 2023-07-26 13:55 UTC
