### ISSUE TITLE
[BUG] new page in context open when execute javascript from page object

### ISSUE THREAD

**Issue by ephung01** [microsoft/playwright-java#160] opened 2020-12-21 02:42 UTC
when execute the Javascript from the page.evaluate, there is a new page created with url ":".   The page close status is false, but when try to close, the process will get stuck- this also affect when tear down which call browser close.  I am using v 0.17.2 and Microsoft Chromium Edge 86.

![image](https://user-images.githubusercontent.com/6579909/102790033-ea3b0000-4372-11eb-899d-fd5b101d334b.png)

**Comment by yury-s** [comment] 2020-12-21 20:28
I have a speculative fix for this but I'm not sure if it actually addresses your problem. Could you share your code snippet?

**Comment by ephung01** [comment] 2020-12-21 21:30
It's actually 2 issues.   I re-create a simple example and able to reproduce the issue browser.close() hang the process.   It's a simple example test :

import com.microsoft.playwright.*;

import java.nio.file.Paths;

public class Test {
    static Playwright playWright = null;
    static Browser browser =  null;
    static BrowserContext context =  null;
    static Page page = null;
    public static void main(String args[]) throws Exception {
        try {
            playWright = Playwright.create();

            BrowserType browserType = playWright.chromium();
            BrowserType.LaunchOptions options = new BrowserType.LaunchOptions();
            options.executablePath = Paths.get("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
            options.headless = false;
            options.chromiumSandbox = true;
            browser = browserType.launch(options);
            context = browser.newContext(
                    new Browser.NewContextOptions()
                            .withViewport(800, 600));

            page = context.newPage();
            String url = "http://www.microsoft.com";
            page.navigate(url, new Page.NavigateOptions().withWaitUntil(Frame.LoadState.DOMCONTENTLOADED));

            // Wait until document load state is complete
            long durationInMilliseconds = 30000; // 30 seconds
            long timeExpired = System.currentTimeMillis() + durationInMilliseconds;
            boolean status = false;
            while (true) {
                try {
                    String script = "() => { return document.readyState; }";
                    if (((String) page.evaluate("() => { return document.readyState; }")).equals("complete")) {
                        System.out.println("Document state is COMPLETE");
                        status = true;
                        break;
                    }
                } catch (Exception e) {
                    // Do Nothing
                }
                if (System.currentTimeMillis() > timeExpired) {
                    System.out.println("Timeout after " + durationInMilliseconds + " ms");
                    status = false;
                    break;
                } else {
                    System.out.println("Wait...");
                    Thread.sleep(250);
                }
            }

            System.out.println("Ready for apply other action");

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            // tear down
            if (page != null) {
                page.close();
                page = null;
            }
            if (browser != null) {
                browser.close();
                browser = null;
            }
            if (context != null) {
                context.close();
                context = null;
            }
            if (playWright != null) {
                playWright.close();
                playWright = null;
            }
        }
    }
}

**Comment by ephung01** [comment] 2020-12-21 21:49
The other issue with additional page generated is when you visit an url which has javascript submit to different url on onload event  (this is  the Single-Sign-On implementation).   It's look like additional the page is created and inaccessible (when visit this page the whole process will hang).   Hopefully your fix will have this zombie page removed from browser context.

**Comment by yury-s** [comment] 2020-12-22 00:22
My fix only ensures that `page.isClosed()` reflects current state of the page and that page.close() in that case will be a no-op.

> I re-create a simple example and able to reproduce the issue browser.close() hang the process.

Which version of Edge is it? Also can you check if it works with bundled Chromium?

Also can you run the test with `DEBUG=pw:protocol` environment variable and attache the protocol logs to this issue?

**Comment by ephung01** [comment] 2020-12-22 00:33
I am using Microsoft Edge Version 86.0.622.56 (Official build) (64-bit)
Playwright java I use latest version 0.170.3

**Comment by ephung01** [comment] 2020-12-22 07:35
When I tried to reproduce at home.  It seems to work fine with the exactly the same version Microsoft Edge 86.0.622.56 and it is working fine.   During this test, I think I might know the issue.   After I installed Microsoft Edge 86.0.622.56 at home, and open the browser it will automatically update to v87.   I have to uninstalled it, disabled my wifi, reinstalled it, and deleted the MicrosoftEdgeUpdate directory to prevent auto update take place.   After the successful test, I hav e a theory that the process in workplace got stuck because when Playwright open browser, it is trying to update the Browser to newer version but got block because the update require admin user privilege.  The process hang by waiting for admin login and never get kill or get timeout.

     I have tried to send couple different chrome/chromium flags as options arguments to disable update, but they do not seem to work.  I will request the system admin to remove Microsoft Edge Update folder and test again
.   
Sorry I am unable to upload attachment due to firewall - and file is too large to past in comment. > 65536 chracters

**Comment by ephung01** [comment] 2020-12-23 16:48
I've deleted the update and the process still hang.   I am passing couple last line of the protocol log hope it will help (I think ending would be important since it get hang on the closing browser).   Look like some kind of NETWORK log fail.

Protocol log:

2020-12-23T16:43:51.050Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"12988.116","loaderId":"3BF4DEE53A49466CEFC9DE8C93474098","documentURL":"https://www.microsoft.com/en-us/","request":{"url":"https://dpm.demdex.net/id?d_visid_ver=2.3.0&d_fieldgroup=MC&d_rtbd=json&d_ver=2&d_orgid=EA76ADE95776D2EC7F000101%40AdobeOrg&d_nsid=0&ts=1608741831039","method":"GET","headers":{"Referer":"https://www.microsoft.com/","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56","Content-Type":"application/x-www-form-urlencoded"},"mixedContentType":"none","initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"timestamp":1139.236618,"wallTime":1608741831.043116,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"fireCORS","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":10,"columnNumber":28555},{"functionName":"f._loadData","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":10,"columnNumber":8042},{"functionName":"f._getRemoteField","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":10,"columnNumber":15498},{"functionName":"f.getMarketingCloudVisitorID","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":10,"columnNumber":16556},{"functionName":"o","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":13,"columnNumber":2430},{"functionName":"o.getInstance","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":14,"columnNumber":583},{"functionName":"","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":19,"columnNumber":22}]}},"type":"XHR","frameId":"3C9C1B5AAEF22BA56EA1DEFECA6C20F3","hasUserGesture":true},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.051Z pw:protocol ◀ RECV {"method":"Page.frameAttached","params":{"frameId":"1C1BF1D954F1B7E48B689BFF2063BB00","parentFrameId":"3C9C1B5AAEF22BA56EA1DEFECA6C20F3","stack":{"callFrames":[{"functionName":"c","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":145,"columnNumber":278},{"functionName":"attachIframe","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":148,"columnNumber":374},{"functionName":"H","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":274,"columnNumber":74},{"functionName":"window.DIL.window.DIL","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":276,"columnNumber":414},{"functionName":"create","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":285,"columnNumber":43},{"functionName":"","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":414,"columnNumber":19}]}},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.051Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"1C1BF1D954F1B7E48B689BFF2063BB00","loaderId":"43415CFE307464B682C4C7ACA2DF94FC","name":"init","timestamp":1139.243275},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.051Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"1C1BF1D954F1B7E48B689BFF2063BB00","loaderId":"43415CFE307464B682C4C7ACA2DF94FC","name":"DOMContentLoaded","timestamp":1139.243787},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.052Z pw:protocol ◀ RECV {"method":"Page.frameStartedLoading","params":{"frameId":"1C1BF1D954F1B7E48B689BFF2063BB00"},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.052Z pw:protocol ◀ RECV {"method":"Network.dataReceived","params":{"requestId":"13384.9","timestamp":1139.244067,"dataLength":24759,"encodedDataLength":24622},"sessionId":"AFC3151E3B2F50DAB5A992EA37215589"}
2020-12-23T16:43:51.054Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"32BADEC959666CCFC093CF8C0E460139","loaderId":"32BADEC959666CCFC093CF8C0E460139","documentURL":"https://mscom.demdex.net/dest5.html?d_nsid=0","request":{"url":"https://mscom.demdex.net/dest5.html?d_nsid=0","urlFragment":"#https%3A%2F%2Fwww.microsoft.com%2Fen-us%2F","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56","Referer":"https://www.microsoft.com/"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"timestamp":1139.246847,"wallTime":1608741831.053796,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"c","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":145,"columnNumber":278},{"functionName":"attachIframe","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":148,"columnNumber":374},{"functionName":"H","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":274,"columnNumber":74},{"functionName":"window.DIL.window.DIL","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":276,"columnNumber":414},{"functionName":"create","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":285,"columnNumber":43},{"functionName":"","scriptId":"44","url":"https://www.microsoft.com/onerfstatics/marketingsites-eus-prod/_h/9ae23327/mscom.statics/externalscripts/mscomhp/audiencemanager.js","lineNumber":414,"columnNumber":19}]}},"type":"Document","frameId":"1C1BF1D954F1B7E48B689BFF2063BB00","hasUserGesture":false},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.055Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"2096D8854355157CE68F5394796AABC2","loaderId":"","documentURL":"https://dapadobeproxy7498us.azurewebsites.net/api/Rank?code=rlRDIZ7WqaYtj2q0tBnzcXtqYumi1dLif6kanCcPh8TZUmshkrAopA==&x-api=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxNyIsIm5iZiI6MTYwNzM2NDA3NywiZXhwIjoxNjA4ODMyODc3LCJpYXQiOjE2MDczNjQwNzcsImlzcyI6Imh0dHA6Ly93d3cuYWRvYmV0YXJnZXQuY29tIiwiYXVkIjoiaHR0cDovL3d3dy5NaWNyb3NvZnQuY29tIn0.dcTp4DKF4TNQFhkOwaLOZK6O8dPQ8wB1zdVZwGwbNFE","request":{"url":"https://dapadobeproxy7498us.azurewebsites.net/api/Rank?code=rlRDIZ7WqaYtj2q0tBnzcXtqYumi1dLif6kanCcPh8TZUmshkrAopA==&x-api=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxNyIsIm5iZiI6MTYwNzM2NDA3NywiZXhwIjoxNjA4ODMyODc3LCJpYXQiOjE2MDczNjQwNzcsImlzcyI6Imh0dHA6Ly93d3cuYWRvYmV0YXJnZXQuY29tIiwiYXVkIjoiaHR0cDovL3d3dy5NaWNyb3NvZnQuY29tIn0.dcTp4DKF4TNQFhkOwaLOZK6O8dPQ8wB1zdVZwGwbNFE","method":"OPTIONS","headers":{"Accept":"*/*","Access-Control-Request-Method":"POST","Access-Control-Request-Headers":"content-type,ocp-apim-subscription-key","Origin":"https://www.microsoft.com","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56","Sec-Fetch-Mode":"cors"},"initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"timestamp":1139.248605,"wallTime":1608741831.055503,"initiator":{"type":"other","url":"https://dapadobeproxy7498us.azurewebsites.net/api/Rank?code=rlRDIZ7WqaYtj2q0tBnzcXtqYumi1dLif6kanCcPh8TZUmshkrAopA==&x-api=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxNyIsIm5iZiI6MTYwNzM2NDA3NywiZXhwIjoxNjA4ODMyODc3LCJpYXQiOjE2MDczNjQwNzcsImlzcyI6Imh0dHA6Ly93d3cuYWRvYmV0YXJnZXQuY29tIiwiYXVkIjoiaHR0cDovL3d3dy5NaWNyb3NvZnQuY29tIn0.dcTp4DKF4TNQFhkOwaLOZK6O8dPQ8wB1zdVZwGwbNFE"},"type":"Other","hasUserGesture":false},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.070Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSentExtraInfo","params":{"requestId":"12988.117","associatedCookies":[{"blockedReasons":["NotOnPath","DomainMismatch"],"cookie":{"name":"ONERFSSO","value":"1","domain":"www.microsoft.com","path":"/en-us","expires":-1,"size":9,"httpOnly":false,"secure":false,"session":true,"priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"isFirstSession","value":"1","domain":"www.microsoft.com","path":"/","expires":-1,"size":15,"httpOnly":true,"secure":true,"session":true,"sameSite":"None","priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"X-FD-FEATURES","value":"ids=sfwaab%2catperf680t2%2c4722t1%2c8110c%2c6424t1%2c7008c%2c5480t1%2c5340t7%2ctasmigration010%2ccartemberpl%2cdisablenorefunds%2cdaconvertenabled%2c6750t1%2c6474t1%2cenablescarlettmetadata&imp=1d9553d3-1a17-4c55-9be7-09ae849dbb99","domain":"www.microsoft.com","path":"/","expires":1640277830.980432,"size":243,"httpOnly":true,"secure":true,"session":false,"priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"X-FD-Time","value":"1","domain":"www.microsoft.com","path":"/","expires":1608742130.98048,"size":10,"httpOnly":true,"secure":true,"session":false,"sameSite":"None","priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"akacd_OneRF","value":"1616517829~rv=27~id=c82986e20eba87fd219a83267bc2bdd4","domain":"www.microsoft.com","path":"/","expires":1616517829.747229,"size":63,"httpOnly":false,"secure":true,"session":false,"sameSite":"None","priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"MSFPC","value":"GUID=e35a4f92c27e432d818ec13825a661b4&HASH=e35a&LV=202012&V=4&LU=1608741830516","domain":"www.microsoft.com","path":"/","expires":1640277830,"size":83,"httpOnly":false,"secure":true,"session":false,"sameSite":"None","priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"ms-cart-order-ids-US","value":"t%3af750c8a1-8180-4fac-9f3e-c972b4a58ca2%3a3137102833","domain":"www.microsoft.com","path":"/","expires":-1,"size":73,"httpOnly":false,"secure":true,"session":true,"priority":"Medium"}},{"blockedReasons":["DomainMismatch"],"cookie":{"name":"SM","value":"T","domain":".c1.microsoft.com","path":"/","expires":-1,"size":3,"httpOnly":false,"secure":false,"session":true,"priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"MUID","value":"0F0D7A34326D65583EA0759D33B364C4","domain":".microsoft.com","path":"/","expires":1642437832.038755,"size":36,"httpOnly":false,"secure":false,"session":false,"priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"check","value":"true","domain":".microsoft.com","path":"/","expires":-1,"size":9,"httpOnly":false,"secure":false,"session":true,"priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"mbox","value":"session#54c0ea09871840be982050d2809d48c1#1608743691|PC#54c0ea09871840be982050d2809d48c1.34_0#1671986631","domain":".microsoft.com","path":"/","expires":1671986631,"size":107,"httpOnly":false,"secure":false,"session":false,"priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"mboxEdgeCluster","value":"34","domain":".microsoft.com","path":"/","expires":1608743690,"size":17,"httpOnly":false,"secure":false,"session":false,"priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"MC1","value":"GUID=e35a4f92c27e432d818ec13825a661b4&HASH=e35a&LV=202012&V=4&LU=1608741830516","domain":".microsoft.com","path":"/","expires":1640277831.529979,"size":81,"httpOnly":false,"secure":true,"session":false,"sameSite":"None","priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"MS0","value":"716f59ee94374f9c8596cb328aec3c61","domain":".microsoft.com","path":"/","expires":1608743631.530065,"size":35,"httpOnly":false,"secure":true,"session":false,"sameSite":"None","priority":"Medium"}},{"blockedReasons":[],"cookie":{"name":"AMCV_EA76ADE95776D2EC7F000101%40AdobeOrg","value":"-894706358%7CMCIDTS%7C18620%7CvVersion%7C2.3.0","domain":".microsoft.com","path":"/","expires":1671813831,"size":86,"httpOnly":false,"secure":false,"session":false,"priority":"Medium"}}],"headers":{"Host":"web.vortex.data.microsoft.com","Connection":"keep-alive","Content-Length":"1046","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56","Content-Type":"text/plain;charset=UTF-8","Accept":"*/*","Origin":"https://www.microsoft.com","Sec-Fetch-Site":"same-site","Sec-Fetch-Mode":"no-cors","Sec-Fetch-Dest":"empty","Referer":"https://www.microsoft.com/","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9","Cookie":"MUID=0F0D7A34326D65583EA0759D33B364C4; check=true; mbox=session#54c0ea09871840be982050d2809d48c1#1608743691|PC#54c0ea09871840be982050d2809d48c1.34_0#1671986631; mboxEdgeCluster=34; MC1=GUID=e35a4f92c27e432d818ec13825a661b4&HASH=e35a&LV=202012&V=4&LU=1608741830516; MS0=716f59ee94374f9c8596cb328aec3c61; AMCV_EA76ADE95776D2EC7F000101%40AdobeOrg=-894706358%7CMCIDTS%7C18620%7CvVersion%7C2.3.0"}},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.079Z pw:protocol ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"32BADEC959666CCFC093CF8C0E460139","timestamp":1139.27243,"type":"Document","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.080Z pw:protocol ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"E6F3B5BDF26545C60973CAF6EB6102C8","timestamp":1139.273688,"type":"Document","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.081Z pw:protocol ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"FFCE6280F9AD96CB0CEBEC24511A1A39","timestamp":1139.274803,"type":"Document","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.082Z pw:protocol ◀ RECV {"method":"Target.detachedFromTarget","params":{"sessionId":"AFC3151E3B2F50DAB5A992EA37215589","targetId":"5D8DC3BDA84C953739549E1024D49F44"},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.082Z pw:protocol SEND ► {"id":39,"method":"Page.enable","sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.084Z pw:protocol ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"7AAF29A1DB9096B7DAD98D9A1365423C","timestamp":1139.276831,"type":"Document","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":"4944536E096CF7F8B7225E53F6C99BF1"}
2020-12-23T16:43:51.084Z pw:protocol ◀ RECV {"method":"Target.detachedFromTarget","params":{"sessionId":"4944536E096CF7F8B7225E53F6C99BF1","targetId":"3C9C1B5AAEF22BA56EA1DEFECA6C20F3"}}
2020-12-23T16:43:51.094Z pw:protocol ◀ RECV {"id":-9999,"result":{}}

**Comment by yury-s** [comment] 2020-12-23 19:22
From what you say the problem is only reproducible with Edge v86 and is fixed in v87+. It's possible that there were some remote debugging protocol changes on the chromium side after v86 that Playwright relies on. With that said you best bet would be to run it with newer version of Edge, it's unlikely that we'll be able to backport any of the changes to v86.

In general Playwright will work with Edge which is built from the same version of Chromium mentioned at the top of the [landing page](https://github.com/microsoft/playwright-java), Edge built from slightly newer Chromium revisions should also work. As for the old versions - there is no compatibility guarantee.

**Closed by yury-s** 2020-12-23 19:22 UTC
