### ISSUE TITLE
[Question] GraalVM Support

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright-java#403] opened 2021-04-19 23:18 UTC
I was trying to create a native image to run some code using playwright and it seems it can't find the driver.  Was wondering if this was something easy to iron out and support?  This is the error I get when running the native binary:

```
19:11:51.038 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
Create Foo command running
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:46)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:33)
	at com.microsoft.playwright.Playwright.create(Playwright.java:76)
	at com.foo.unwired.CreateFoo.<init>(CreateFoo.java:21)
	at com.foo.unwired.CreateFooCommand.run(CreateFooCommand.java:93)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
	at com.foo.UnwiredCommand.main(UnwiredCommand.java:17)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.playwright.impl.Driver.createDriver(Driver.java:65)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:44)
	... 14 more
Caused by: java.lang.NullPointerException
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:60)
	at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:32)
	... 17 more
```

**Comment by chaganiu** [comment] 2021-04-20 14:32
Looks like this may be a reflection issue.  I found some information on what might be needed: 

https://www.graalvm.org/reference-manual/native-image/Reflection/

**Comment by chaganiu** [comment] 2021-04-20 19:07
after adding in some of the reflection configs I got to this error:

```
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:46)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:33)
	at com.microsoft.playwright.Playwright.create(Playwright.java:76)
	at com.foo.unwired.CreateFoo.<init>(CreateFoo.java:17)
	at com.foo.unwired.CreateFooCommand.run(CreateFoo.java:91)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
	at com.foo.UnwiredCommand.main(UnwiredCommand.java:17)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.playwright.impl.Driver.createDriver(Driver.java:65)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:44)
	... 14 more
Caused by: java.nio.file.FileSystemNotFoundException: Provider "resource" not installed
	at java.nio.file.Path.of(Path.java:212)
	at java.nio.file.Paths.get(Paths.java:97)
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:63)
	at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:32)
	... 17 more
```

**Comment by yury-s** [comment] 2021-04-21 00:53
Do you launch it from a jar or using `mvn` ? Can you share your pom.xml and the command line that you use to launch the test?

> java.nio.file.FileSystemNotFoundException: Provider "resource" not installed

It probably fails to read from .jar file for some reason. Are you using latest playwright version? (I'm asking because there is no code at DriverJar.java:63 in current source base).

**Comment by chaganiu** [comment] 2021-04-21 14:35
i'm using:

```xml
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.9.1-alpha-0</version>
        </dependency>
```

my understanding is that graalvm creates a jar and then uses that jar to build a native app.  I'm running it from this native app.

The entire process to set this up is this:

I'm using [sdk man](https://sdkman.io/) to install java so i use that to install graalvm.

1. Install graalvm: `sdk install java 21.0.0.2.r11-grl`
2. Use graalvm: `sdk use java 21.0.0.2.r11-grl`
3. [Add graalvm native image dependencies to pom](https://www.graalvm.org/reference-manual/native-image/NativeImageMavenPlugin/)
4. write code:  I'm using [picocli](https://picocli.info/) to create a cli app
5. run `mvn package` which will build a jar and a native app
6. run the native app.  in my case it's just doing `./demo runTest`


As far as `DriverJar.java` not being in the codebase, isn't this it: https://github.com/microsoft/playwright-java/blob/master/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java?

**Comment by yury-s** [comment] 2021-04-21 17:56
> 4. write code:  I'm using [picocli](https://picocli.info/) to create a cli app
> 5. run `mvn package` which will build a jar and a native app

I don't know anything about who picoli works, but the problem is likely in how it figures out which dependencies to pack and how. The issue sounds very similar to Springboot problem described in #306.

> As far as `DriverJar.java` not being in the codebase, isn't this it: https://github.com/microsoft/playwright-java/blob/master/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java?

Yes, that's the one. `playwright` artifact depends on `driver-bundle` which contains DriverJar. From the stack trace it DriverJar seems to be loaded just fine, the problem happens when it tries to unpack playwright driver. #342 was committed after v1.9.1-alpha-0, so the first version to include it is 1.10.0. Can you try updating playwright to 1.10.0 and see if the problem persists?

**Comment by chaganiu** [comment] 2021-04-21 19:05
I don't think it is a picocli issue.  I removed everything except playwright (tried 1.10.0) and graalvm and I still see the same issue.  When I just print out something to the console (see commented code in main class below) i don't get any errors so i know the graalvm part is working correctly.  When i try to use playwright I have the problems i mentioned in the above comments.

Here is my pom and code:

##### pom.xml
```java
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.1</version>
    <packaging>${packaging}</packaging>

    <properties>
        <packaging>jar</packaging>
        <jdk.version>11</jdk.version>
        <release.version>11</release.version>
        <graalvm.version>21.0.0.2</graalvm.version>
        <exec.mainClass>com.example.DemoCommand</exec.mainClass>
    </properties>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>${graalvm.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.10.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>${release.version}</release>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.graalvm.nativeimage</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>${graalvm.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <skip>false</skip>
                    <imageName>demo</imageName>
                    <buildArgs>
                        --no-fallback
                    </buildArgs>
                    <mainClass>${exec.mainClass}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

##### main class
```java
package com.example;

import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;

import java.nio.file.Paths;

public class DemoCommand {

    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            var browser = playwright.webkit().launch();
            var page = browser.newPage();
            page.navigate("http://whatsmyuseragent.org/");
            page.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("example.png")));
        }

        // System.out.println("hello world");
    }
}

```

**Comment by yury-s** [comment] 2021-04-28 19:48
Closing per the explanation above. With native-image you need a custom configuration for the bundled resources, writing such config is out of our project's scope at the moment. With that said all the source code is available and if someone wants to do it I could help by answering specific questions.

**Closed by yury-s** 2021-04-28 19:48 UTC

**Comment by Jeiwan** [comment] 2022-04-27 05:43
I'm having the same problem. After adding the driver bundle resources into the binary, it fails with this:
```
...
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at renderer2.playwright$create.invokeStatic(playwright.clj:17)
	at renderer2.pool$allocator$reify__1401.allocate(pool.clj:26)
	at stormpot.ReallocatingAdaptor.allocate(ReallocatingAdaptor.java:37)
	at stormpot.BAllocThread.alloc(BAllocThread.java:255)
	at stormpot.BAllocThread.increaseSizeByAllocating(BAllocThread.java:152)
	at stormpot.BAllocThread.replenishPool(BAllocThread.java:113)
	at stormpot.BAllocThread.continuouslyReplenishPool(BAllocThread.java:97)
	at stormpot.BAllocThread.run(BAllocThread.java:89)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystemProvider.getFileSystem(NativeImageResourceFileSystemProvider.java:144)
	at com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystemProvider.getPath(NativeImageResourceFileSystemProvider.java:154)
	at java.nio.file.Path.of(Path.java:208)
	at java.nio.file.Paths.get(Paths.java:98)
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:90)
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:44)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
```

This leads here:
https://github.com/microsoft/playwright-java/blob/release-1.21/driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java#L91

Since GraalVM binary is not a jar, it doesn't create a new filesystem, but it needs to.

**Comment by Jeiwan** [comment] 2022-04-29 00:12
I fixed the above exception by creating a filesystem for URI "resource:/".

Another problem was `com.microsoft.playwright.impl.Message` encoding/decoding in Gson. Fixed by creating this file:
```json
[
  {
    "name": "com.microsoft.playwright.impl.Message",
    "unsafeAllocated": true
  }
]
```
And setting `-H:ReflectionConfigurationFiles=./reflect-config.json` in the native-image command.

Now, it hangs at `Playwright.create()`, and I have it killed after a timeout (2 minutes in my case). I enabled debug logs:
```
export DEBUG=pw:install,pw:api,pw:channel
```
This is the last log it prints before freezing:
> ◀ RECV {"id":1,"result":{"playwright":{"guid":"Playwright"}}}

In `CreateOptions` I only set "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD" so it doesn't download browsers (they're pre-installed).

Any ideas?

**Comment by Jeiwan** [comment] 2022-05-09 05:14
I've managed to extract stacktrace:
```
[com.oracle.svm.core.posix.headers.Pthread pthread_cond_timedwait Pthread.java -1]
[com.oracle.svm.core.posix.thread.PosixParkEvent condTimedWait PosixPlatformThreads.java 287]
[com.oracle.svm.core.thread.PlatformThreads parkCurrentPlatformOrCarrierThread PlatformThreads.java 811]
[jdk.internal.misc.Unsafe park Unsafe.java 52]
[java.util.concurrent.locks.LockSupport parkNanos LockSupport.java 252]
[java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject awaitNanos AbstractQueuedSynchronizer.java 1672]
[java.util.concurrent.ArrayBlockingQueue poll ArrayBlockingQueue.java 435]
[com.microsoft.playwright.impl.PipeTransport poll PipeTransport.java 68]
[com.microsoft.playwright.impl.TransportLogger poll TransportLogger.java 27]
[com.microsoft.playwright.impl.Connection processOneMessage Connection.java 157]
[com.microsoft.playwright.impl.ChannelOwner runUntil ChannelOwner.java 101]
[com.microsoft.playwright.impl.Connection sendMessage Connection.java 105]
[com.microsoft.playwright.impl.ChannelOwner sendMessage ChannelOwner.java 94]
[com.microsoft.playwright.impl.Connection$Root initialize Connection.java 76]
[com.microsoft.playwright.impl.Connection initializePlaywright Connection.java 138]
[com.microsoft.playwright.impl.PlaywrightImpl create PlaywrightImpl.java 47]
[com.microsoft.playwright.Playwright create Playwright.java 96]
```

This seems like thread locking. This happens only in the native image, and never happens when running a jar.

**Comment by Jeiwan** [comment] 2022-05-10 02:35
New findings! It's more like incorrect Message decoding rather than thread locking. I uncommented these println's and this is what I got:
1. When running via `java -jar`:
    ```
    Message: __create__ 0
    2022-05-10T02:26:53.418Z ◀ RECV {"id":1,"result":{"playwright":{"guid":"Playwright"}}}
    Message: null 1
    Message: 1 Message{id='1', guid='null', method='null', params=null, result='{"playwright":{"guid":"Playwright"}}', error='null'}
    ```
1. When running via Native Image:
    ```
    Message: null 0
    2022-05-10T02:27:23.850Z ◀ RECV {"id":1,"result":{"playwright":{"guid":"Playwright"}}}
    Message: null 0
    ```

**Comment by Jeiwan** [comment] 2022-05-10 06:37
Ok, it works. All that's needed is to properly configure reflections.

Playwright 1.21.0 works on:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```

**Comment by yury-s** [comment] 2022-05-10 17:34
> Ok, it works. All that's needed is to properly configure reflections.

Can you share more on this so that others could benefit from your findings should they face the same issue?

**Comment by Jeiwan** [comment] 2022-05-11 02:56
In my code, I only needed to create a filesystem for resources, otherwise Playwright couldn't load the driver:
```clj
(FileSystems/newFileSystem (URI. "resource:/") {"create" "true"})
```
(this is Clojure)
Also, for Clojure specifically, I needed to add type hints whenever GraalVM complained about missing methods.

All other issues I had were caused by Native Image failing to detect types via reflection. From their docs:
> Native Image has partial support for reflection and needs to know ahead-of-time the reflectively accessed program elements.
[link](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/)

The main difficulty is that exceptions it throws don't make sense. You need to guess what class could cause the exception, and sometimes you need to debug Playwright's code (I needed to uncomment [this line](https://github.com/microsoft/playwright-java/blob/main/playwright/src/main/java/com/microsoft/playwright/impl/Connection.java#L167) to see that `Message` had empty fields after decoding).

Specifically, Native Image fails to detect types during serialization, JSON decoding (e.g. it couldn't fill `Message` fields), type casting, etc. So I ended up with this reflection config:
```json
[
  {
    "name": "com.microsoft.playwright.impl.DriverJar",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.Message",
    "unsafeAllocated": true,
    "fields": [
      { "name": "id" },
      { "name": "guid" },
      { "name": "method" },
      { "name": "params" },
      { "name": "result" },
      { "name": "error" }
    ]
  },
  {
    "name": "com.microsoft.playwright.Browser$NewContextOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.ViewportSize",
    "unsafeAllocated": true,
    "fields": [
      { "name": "width" },
      { "name": "height" }
    ],
    "methods": [
      { "name": "<init>", "parameterTypes": ["int", "int"] }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.HttpHeader",
    "unsafeAllocated": true,
    "fields": [
      { "name": "name" },
      { "name": "value" }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.Timing",
    "unsafeAllocated": true,
    "fields": [
      { "name": "startTime" },
      { "name": "domainLookupStart" },
      { "name": "domainLookupEnd" },
      { "name": "connectStart" },
      { "name": "secureConnectionStart" },
      { "name": "connectEnd" },
      { "name": "requestStart" },
      { "name": "responseStart" },
      { "name": "responseEnd" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedArgument",
    "fields": [
      { "name": "value" },
      { "name": "handles" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedValue",
    "fields": [
      { "name": "n" },
      { "name": "b" },
      { "name": "s" },
      { "name": "v" },
      { "name": "d" },
      { "name": "r" },
      { "name": "a" },
      { "name": "o" },
      { "name": "h" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedValue$O",
    "fields": [
      { "name": "k" },
      { "name": "v" }
    ]
  },
  {
    "name": "com.microsoft.playwright.ElementHandle$ScreenshotOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.Locator$ElementHandleOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.Frame$WaitForSelectorOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  }
]
```
This list can be different depending on what features of Playwright you're using. For example, I needed to add fields for `SerializedValue$O` because a map that I passed as the second argument to `Page.evaluate()` was encoded as `undefined`.

This is how I compile the binary:
```
native-image \
  --report-unsupported-elements-at-runtime \
  --initialize-at-build-time \
  --no-server \
  -jar ./target/uberjar/app-standalone.jar \
  -H:Name=./target/app \
  -H:IncludeResources=.* \
  -H:ReflectionConfigurationFiles=./reflect-config.json
```
(some of these flags are Clojure specific)
