### ISSUE TITLE
[Bug]: Webkit Mobile View: Stream error in the HTTP/2 framing layer: Facing this issue upon opening https://www.redbus.in

### ISSUE THREAD

**Issue by Krishna-D-Hegde** [microsoft/playwright-java#1667] opened 2024-09-08 17:47 UTC
### Version

1.46.0

### Steps to reproduce

Playwright playwright = Playwright.create();
		Browser browser = playwright.webkit().launch(new BrowserType.LaunchOptions().setHeadless(false));
        BrowserContext context = browser.newContext(
        new Browser.NewContextOptions()
        		.setViewportSize(414, 896) // iPhone 12 viewport size
                .setDeviceScaleFactor(3)   // Device pixel ratio
        		.setUserAgent("Mozilla/5.0 (iPhone14,6; U; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/19E241 Safari/602.1") // iPhone 12 user agent
                .setHasTouch(true)         // Enable touch events
                .setIgnoreHTTPSErrors(true) // Optional: ignore HTTPS issues if applicable
                .setExtraHTTPHeaders(Map.of("connection", "close")) // Disable HTTP/2
                .setIsMobile(true)  // Set to true for mobile
        		);       
        Page page = context.newPage();
        page.navigate("https://www.redbus.in");

### Expected behavior

https://www.redbus.in should open in Webkit Mobile View

### Actual behavior

Works for Chromium Mobile view and Firefox Mobile view but not working for Webkit Mobile view

### Environment

Windows - Webkit

**Comment by mxschmitt** [comment] 2024-09-17 09:14
Sorry for the late reply. Minimal reproducible for Node.js:

```ts
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({ headless: false });
  
  const context = await browser.newContext({
    userAgent: "Mozilla/5.0 (iPhone14,6; U; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/19E241 Safari/602.1", // iPhone 12 user agent
  });

  const page = await context.newPage();
  await page.goto("https://www.redbus.in");

})();
```

**Comment by mxschmitt** [comment] 2024-09-17 12:32
Closing as per above, since it also doesn't work with cURL. So the web server is definitely broken or returns invalid http2. I recommend to use a different user-agent as workaround.

**Closed by mxschmitt** 2024-09-17 12:32 UTC
