### ISSUE TITLE
Playwright-Typescript[BUG] - File explorer is open always.

### ISSUE THREAD

**Issue by rubini881213** [microsoft/playwright-java#1473] opened 2024-02-05 06:58 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code
async addImages() {
 const dm=5;
        for(let i=1; i<=dm; i++){
        await this.page.getByPlaceholder('Enter new layer').click();
        await this.page.getByPlaceholder('Enter new layer').fill(`layer ${i}`);
        await this.page.getByText('Add').nth(0).click();
        await this.page.waitForLoadState("domcontentloaded");
        await this.page.getByRole('button', { name: `layer ${i}` }).click();
        await this.page.waitForLoadState("domcontentloaded");
        await this.page.locator('div').filter({ hasText: /^Upload Image$/ }).nth(1).click();
        await this.page.setInputFiles("input[type='file'][accept='image/png,.png']", [
          'uploads/Rose.png',
          'uploads/image.png'
        ]);
        await this.page.waitForLoadState("domcontentloaded");
        }
        }
        
 I tried to upload images inside the 5 layers. But, Images are uploaded only in the layer 1. Images are not uploaded in other layers due to 5 file explorer is opened always. Can you pls suggest any ways to handle it & upload images for all the 5 layers ?

**Comment by yury-s** [comment] 2024-02-05 17:26
Closing as it is not a bug in playwright. Please follow our [debugging guide](https://playwright.dev/java/docs/debug) to see where you script may be failing and why. I you believe this is a bug in playwright, please file a new issue and attach a repro that we could run to reproduce the problem.

**Closed by yury-s** 2024-02-05 17:26 UTC
