### ISSUE TITLE
[BUG] Can't run in Springboot  application

### ISSUE THREAD

**Issue by cyrly97** [microsoft/playwright-java#306] opened 2021-02-26 02:59 UTC
When I use spring-boot-maven-plugin to build a jar and  use ` java -jar demo.jar`, it dosen't run and throws exception.

java.nio.file.NoSuchFileException: /BOOT-INF/lib/driver-bundle-0.180.0.jar!/driver/win32_x64
        at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666)
        at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
        at java.nio.file.Files.readAttributes(Unknown Source)
        at java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.FileTreeIterator.<init>(Unknown Source)
        at java.nio.file.Files.walk(Unknown Source)
        at java.nio.file.Files.walk(Unknown Source)
        at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:58)
        at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:18)
        ... 17 more

**Comment by yury-s** [comment] 2021-02-26 23:06
Looks like spring-boot-maven-plugin didn't include the driver-bundle into the final jar, can you share more details about your build configuration?

**Comment by cyrly97** [comment] 2021-03-01 02:37
> Looks like spring-boot-maven-plugin didn't include the driver-bundle into the final jar, can you share more details about your build configuration?

I dubug the source code,and find exception at Line 64 of `DriverJar.java` .This doesn't apply to the jar which is made by spring-boot-maven-plugin.
![企业微信截图_16145662384716](https://user-images.githubusercontent.com/43930599/109445250-2af17c80-7a7a-11eb-8793-2c008b6968a6.png)

**Comment by AhmedRiyad** [comment] 2021-03-03 12:02
@yury-s I had the same issue, and after debugging, I found that this line of code `Path relative = srcRoot.relativize(fromPath);` in `DriverJar.java` is not working as expected in this case.

e.g. srcRoot was `/driver/mac/` and fromPath was `'/driver/mac/playwright.sh'` and the result was `../mac/playwright.sh`

<img width="1685" alt="Screen Shot 2021-03-03 at 1 39 10 PM" src="https://user-images.githubusercontent.com/6626468/109800470-e276c200-7c25-11eb-93e5-4f6b3626af05.png">

I'm not an expert in Java, but it gave me the correct result when I tried this way.

`Paths.get(srcRoot.toString()).relativize(Paths.get(fromPath.toString()))`

**Comment by yury-s** [comment] 2021-03-03 18:29
Thanks @AhmedRiyad for investigating this, this is very odd as what I see on mac is the following:

![image](https://user-images.githubusercontent.com/9798949/109852996-43909c80-7c0a-11eb-9a8a-f148d6bb4f46.png)

So it looks like the problem is that in your case the classloader and the jar filesystem implementation are different leading to the wrong path resolution, is there a simple test project that reproduces the problem? I can apply the fix you suggest but I'd like to have a way to reproduce the problem.

**Comment by AhmedRiyad** [comment] 2021-03-04 08:17
Thanks a lot, @yury-s, for your prompt response. Unfortunately, I don't have a simple test project.

**Comment by yury-s** [comment] 2021-03-04 17:01
@AhmedRiyad  no problem, would be nice if you or @cyrly97 checked that the fix actually resolves the problem. It's currently available in `0.190.0-SNAPSHOT`.

**Comment by arkasandr** [comment] 2021-03-04 21:07
I had the same problem with 0.180.0 version. I've manually added to \lib\driver-bundle-0.180.0.jar in my project and start with
 -Dloader.path=lib/ org.springframework.boot.loader.PropertiesLauncher in my Dockerfile. And everything is good now.

**Comment by moikeygraham** [comment] 2021-03-05 14:04
@yury-s I believe this still isn't fixed... I checked out and built 0.190.0-SNAPSHOT and the problem still exists for a spring boot application running on command-line using `-jar` arg.

I've uploaded a basic demo repo of a simple Spring Boot project with standard packaging configuration here:
- https://github.com/moikeygraham/playwright-driver-classpath-issue

Java version: 11.0.6
Reproduce steps:
- run `mvn package`
- execute `java -jar ./target/demo-0.0.1-SNAPSHOT.jar`

```
Caused by: java.nio.file.NoSuchFileException: /BOOT-INF/lib/driver-bundle-0.190.0-SNAPSHOT.jar!/driver/mac
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(ZipPath.java:729) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:293) ~[jdk.zipfs:na]
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[na:na]
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[na:na]
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71) ~[na:na]
	at java.base/java.nio.file.Files.walk(Files.java:3822) ~[na:na]
	at java.base/java.nio.file.Files.walk(Files.java:3876) ~[na:na]
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:69) ~[driver-bundle-0.190.0-SNAPSHOT.jar!/:na]
	at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:32) ~[driver-bundle-0.190.0-SNAPSHOT.jar!/:na]
	... 23 common frames omitted
```

**Comment by AhmedRiyad** [comment] 2021-03-05 19:42
@yury-s I have just tried, and the issue has been fixed in my case. Thanks a lot, really appreciated.

**Comment by arkasandr** [comment] 2021-03-06 15:14
@yury Everything is good with adding 1.9.0-alpha-0 version to pom.xml. 
`-Dloader.path=lib/ org.springframework.boot.loader.PropertiesLauncher`
 is no longer needed in my case. 
Thanks a lot!

**Comment by yury-s** [comment] 2021-03-11 19:01
@moikeygraham thanks for the repro, I managed to reproduce it locally. I'll look at what we can do in that case, we should probably detect that it is a jar in another jar.

**Closed** 2021-03-12 07:58 UTC

**Comment by yury-s** [comment] 2021-03-12 08:02
@moikeygraham the fix is now available in `1.10.0-SNAPSHOT`, can you give it a try?

**Comment by moikeygraham** [comment] 2021-03-12 09:19
@yury-s 1.10.0-SNAPSHOT fixes the issue in my case... thanks!

Though I think the fix would not work if further nesting / layering of the .jar occurred? I spent too much time debugging an "ultimate" fix for this and discovered cascading number of issues & limitations around layered jars, mostly with JDK NIO zipfs module:
- accessing nested zipfs using a parent fs is only possible in JDK12+ and above, and can only be done using `Path` not `URI`
- obtaining a layered zip(jar) filesystem is not straight-forward with `java.nio.file.Filesystem` because URI's are not layered
  - in Spring Boot case above, the jar URI should really be `jar:jar:/playwright.jar!/driver-bundle.jar!/driver/linux` but JDK does not do this... would allow us to recursively parse the URI layers into `Path`'s 
- possibly the `relativize` bug above are related to bugs in the JDK for zipfs. it explains why the default fs fixed resolved the issue....
  - https://bugs.openjdk.java.net/browse/JDK-8211385
  - https://bugs.openjdk.java.net/browse/JDK-8211919

**Comment by AlmazSamatov** [comment] 2021-03-19 21:42
@moikeygraham how you have used 1.10.0-SNAPSHOT? It can be imported from maven. Have you builded from sources?

**Comment by AlmazSamatov** [comment] 2021-03-19 22:16
@yury-s how to use 1.10.0-SNAPSHOT from maven?

**Comment by moikeygraham** [comment] 2021-03-20 16:11
@AlmazSamatov yes I built from src & installed to local maven repo

**Comment by drrodio** [comment] 2021-03-22 14:32
Hi @yury-s, we are facing the same problem above, when do you think the release with this fix would it be ready?

Thanks in advance
