### ISSUE TITLE
[BUG] Special French characters in HTML elements break Playwright

### ISSUE THREAD

**Issue by DivyaWal7** [microsoft/playwright-java#1328] opened 2023-06-28 11:29 UTC
### System info
- Playwright Version: [v1.30] 
- Operating System: [All, Windows 11, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

**Library used for Playwright Object**
```java
import com.microsoft.playwright.Playwright;
``` 

**In code below : playwrightObjects is  a class which contains Playwright object**
```java
Page page = playwrightObjects.getPage();
``` 

**Here addInitScript is a function of playwright that uses the JSON file to merge values in the document**
```java
page.addInitScript(Paths.get(<JSON File Path>));
``` 
 **Below code specifies the addInitScript function of Playwright**
 
```java
  @Override
  public void addInitScript(Path path) {
    withLogging("Page.addInitScript", () -> {
      try {
        byte[] bytes = readAllBytes(path);
        addInitScriptImpl(new String(bytes, UTF_8));
      } catch (IOException e) {
        throw new PlaywrightException("Failed to read script from file", e);
      }
    });
``` 
 **Below code specifies the addInitScriptImpl function of Playwright**
```java
 private void addInitScriptImpl(String script) {
    JsonObject params = new JsonObject();
    params.addProperty("source", script);
    sendMessage("addInitScript", params);
  }
``` 

  **Sample JSON file used**
  
```typescript
 {
 
 "Success_x0020_Factors": "<div class=\"ExternalClass4EC3B32FDF9E4AFD95F5327AD74B57B7\"><p><u>L’entente prévoit aussi un paiement forfaitaire unique de 2500&#160;$ ouvrant droit à pension qui représente 3,6&#160;% de plus du salaire du membre moyen.</u></p><p>TEST Dans son propre communiqué, l’Agence du revenu du Canada déclare qu’avec le syndicat, elle a conclu une entente de principe sur le télétravail en dehors de la convention collective. Les deux parties entreprendront un examen de la directive sur les modalités de travail virtuel et vont créer un comité-conseil qui abordera les préoccupations des employés</p></div>",
  "Title": "Test PPB 1"
 }
``` 

**Expected**

Playwight should provide support for french characters. 

**Actual**

Special characters in French, such as è, é, è, ê, à, â, ë, ï, î, ô, û, ç, œ, ù, ÿ and >> are not recognized by Playwright.
It break the Playwright parser and make these elements on the page not accessible.
We do not get any exception here but the file that comes here is blank i.e without merging the JSON values.

**Please Note :** This issue is affecting the functionality, so it would be greatly appreciated if we could resolve it as soon as possible. We are expecting to close this issue by 3rd July considering the criticality of it.

**Comment by DivyaWal7** [comment] 2023-07-10 05:53
@pavelfeldman  @yury-s  

Can you please assist on the issues ?  This issue is affecting the functionality and we need to close it soon

**Comment by mxschmitt** [comment] 2023-07-10 06:06
This issue still does not contain a minimal reproduction. I was looking into your issue, but was not able to reproduce, since it's not clear for me what you are exactly doing. Can you provide us one which we can run locally?

A file which calls setInitScript with expected and actual output would be super helpful here, thanks for your understanding!

**Comment by mxschmitt** [comment] 2023-07-20 16:07
Closing since we don't have a clear reproduction for this bug report. Please re-file with providing clear reproduction steps, the most preferred way is an example test which breaks by following our getting started: https://playwright.dev/java/docs/intro

**Closed by mxschmitt** 2023-07-20 16:07 UTC

**Comment by DivyaWal7** [comment] 2023-07-24 07:24
Linking with the new issue logged

**Comment by DivyaWal7** [comment] 2023-08-03 04:31
Linking new issue logged with additional info required 
https://github.com/microsoft/playwright-java/issues/1344

**Comment by stahlbauer** [comment] 2024-08-21 11:23
The same problem (still) also exists for German Umlauts. I am using Playwright-Java. With an `hasText` filter.

**Comment by mxschmitt** [comment] 2024-08-21 12:07
> The same problem (still) also exists for German Umlauts. I am using Playwright-Java. With an `hasText` filter.

Please file a separate bug on GitHub, happy to investigate!
