### ISSUE TITLE
[BUG] Browser.close() on client connected over CDP doesn't trigger "disconnected" event on server side

### ISSUE THREAD

**Issue by RG9** [microsoft/playwright-java#1394] opened 2023-09-21 15:05 UTC
Related to: https://github.com/microsoft/playwright-java/issues/912

### System info
- Playwright Version: v1.38.0
- Operating System: Fedora 38
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.
 

**Link to the GitHub repository with the repro**

https://github.com/RG9/remote-playwright-demo

**Steps**
1. In one terminal run "playwright-server":

```
cd playwright-server && npm install && npm run build && npm run start
```

2. In second terminal run "App.java" connecting over CDP:

```
mvn package exec:java
```

**Expected**

I expect printed "browser disconnected event" in logs of "playwright-server", like:
```
Express is listening at http://localhost:3000
browser created at ws://127.0.0.1:3001/devtools/browser/44752463-3b05-4c94-9035-ec1f6449df69
browser disconnected event
```

**Actual**

There is no "browser disconnected event" log entry, which means event is not triggered.
```
Express is listening at http://localhost:3000
browser created at ws://127.0.0.1:3001/devtools/browser/24914a27-4d65-4c30-8476-d560f087a596
```

**Comment by yury-s** [comment] 2023-09-21 18:19
This is working as intended. There are no signals in Playwright API that would tell you if someone connected to the browser over CDP. [on('disconnected')](https://playwright.dev/docs/api/class-browser#browser-event-disconnected) is fired when the browser closes which not necessarily happens if a CDP client disconnects.

Closing the bug as it is working as intended and we are not going to expose any events about CDP clients connection/disconnection.

**Closed by yury-s** 2023-09-21 18:19 UTC

**Comment by RG9** [comment] 2023-09-21 19:26
@yury-s 
Thanks for clarifying!

Just to explain why I thought it was a bug.

1. "disconnected" doc says that it fires on `browser.close()`, which I did in Java code as a client of "playwright-server":
![Screenshot from 2023-09-21 21-15-05](https://github.com/microsoft/playwright-java/assets/4287365/1a195e89-bd5d-4dd0-9aee-8bd6e704df89)

2. Then in `browser.close()` doc I read that it "disconnects from the browser server":
![Screenshot from 2023-09-21 21-15-37](https://github.com/microsoft/playwright-java/assets/4287365/f0fa0195-f0f7-4f35-a233-a33c7df9ea3a)

**Comment by yury-s** [comment] 2023-09-21 19:51
> 1. "disconnected" doc says that it fires on browser.close(), which I did in Java code as a client of "playwright-server":

Correct, it should be fired if you call `browser.close()` on the server where you called `chromium.launch(launchOpts)`

> Then in browser.close() doc I read that it "disconnects from the browser server":

It will disconnect, but this won't trigger any events on the server. The docs are a bit confusing in the context of remote connections.
