### ISSUE TITLE
[Question] How to run play wright java code into Docker 

### ISSUE THREAD

**Issue by techshashank80** [microsoft/playwright-java#458] opened 2021-05-24 19:50 UTC
Hi There,

Can someone guide that on how to run playwright Java code in Docker? I understand that we have to use WebSocket, here is my code:
`playwright = Playwright.create() ;

    playwright.chromium().connect("ws://0.0.0.0:3000/chromium", new BrowserType.ConnectOptions());
    browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false).setArgs(Arrays.asList("--ipc=host","--no sandbox","--disable-dev-shm-usage")).setChromiumSandbox(false));
    context = browser.newContext(new Browser.NewContextOptions());
    page = context.newPage();`
I am trying to run docker using the following command, anything I am missing, please correct.

docker run -it --rm --ipc=host mcr.microsoft.com/playwright/java:focal /bin/bash

I am on a Mac machine, Docker. Above run docker command runs in docker without localhost/port number

**Comment by mxschmitt** [comment] 2021-05-25 11:54
Closing as duplicate of https://github.com/microsoft/playwright/issues/6726#issuecomment-847310121

**Closed by mxschmitt** 2021-05-25 11:54 UTC
