### ISSUE TITLE
[BUG] Accept Incoming network connections dialog

### ISSUE THREAD

**Issue by xadvfh** [microsoft/playwright-java#910] opened 2022-04-22 13:11 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] Tested with 1.19.0, 1.20.1, 1.21.0
- Operating System: [e.g. Windows, Linux or Mac] Mac Monterey 
- Node.js version: [e.g. 12.22, 14.6] Java
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
page.navigate("https://myCompanyUrl.com"
page.waitForTimeout(10000);
```

**Describe the bug**

Something in our application is causing the Accept incoming network connections dialog to get triggered.  I tried to reproduce on other sites but haven't been able to.  I have logs that I gathered via `DEBUG=pw:browser*,pw:protocol` but would prefer to send them privately.

**Comment by yury-s** [comment] 2022-04-22 19:36
Can it be that your application is trying to run a web server and that it requires extra permissions from the system? or might be some JVM debugging port? Playwright itself doesn't listen for incoming traffic normally, can you share the code that triggers the dialog?

**Comment by xadvfh** [comment] 2022-04-25 11:50
> Can it be that your application is trying to run a web server and that it requires extra permissions from the system

Not that I know of.  


@yury-s sent you a slack message with the reproducible snippet.

**Comment by yury-s** [comment] 2022-04-25 19:54
Thanks! I tried that and don't see any dialogs, my hunch is that it is because the VM tries to open debugging port. Try running from terminal, something like this:

```
mvn exec:java  -e -Dexec.mainClass=org.example.Bug
```

**Comment by xadvfh** [comment] 2022-04-25 22:04
@yury-s I still see it when i run `mvn exec:java  -e -Dexec.mainClass=MainClass`.  I don't see it on other sites for my company, only a couple of them.  I have browser and protocol logs that i'm going to send over slack if you wouldn't mind taking a look.  Thank you!

**Comment by yury-s** [comment] 2022-04-25 22:11
Can you post a screenshot of the dialog that you see?

**Comment by xadvfh** [comment] 2022-04-25 22:15
Sure here you go: 
![image](https://user-images.githubusercontent.com/72147686/165183668-3c482d4c-c74b-4fb2-a7b4-d605e369bb2b.png)

**Comment by xadvfh** [comment] 2022-04-29 16:32
@yury-s  yes I can see the dialog when running without playwright using the command you linked

**Comment by yury-s** [comment] 2022-04-29 19:01
Well, that's definitely a Chromium issue then, I believe all the flags we pass should not matter, you can try with the shorter command line and see the same dialog:
```
/Users/xadvfh/Library/Caches/ms-playwright/chromium-1000/chrome-mac/Chromium.app/Contents/MacOS/Chromium --no-sandbox --user-data-dir=/tmp/your-profile
```

It probably has something todo with security settings on your Mac, do you know if this dialog comes from an anti-virus (looks like a system one but want to double check)? The problem is I can't reproduce it to give you an advice.

**Comment by yury-s** [comment] 2022-04-29 19:25
@aslushnikov pointed out that he was fixing similar issue a year ago in https://github.com/microsoft/playwright/pull/8162 and it looks like the feature flag was renamed to [DialMediaRouteProvider](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/mac_build_instructions.md#avoiding-the-incoming-network-connections-dialog), we'll update the flags that we pass to Chromium by default.

Can you confirm that adding the new flag fixes the problem for you?

**Comment by xadvfh** [comment] 2022-04-29 20:09
@yury-s using the short command `/Users/umairchagani/Library/Caches/ms-playwright/chromium-1000/chrome-mac/Chromium.app/Contents/MacOS/Chromium --no-sandbox --user-data-dir=/tmp/your-profile` I see the dialog right away without even navigating to any page.

Adding in `DialMediaRouteProvider` to the `--disabled-features` flag still shows the dialog. 

I also tried this on a personal computer and did NOT see the dialog.  so it must be the work computer.  i guess i'll try digging around.  is it expected to not see it headless but only when headful?

**Comment by yury-s** [comment] 2022-04-29 21:29
> is it expected to not see it headless but only when headful?

Yes, the feature is not available in headless.

**Comment by yury-s** [comment] 2022-05-13 23:36
@xadvfh can you check if it still reproduces with the new release 1.22.0 ?

**Comment by yury-s** [comment] 2022-05-18 19:55
It should be fixed by https://github.com/microsoft/playwright/pull/13854, please file a new issue if it still reproduces on v1.22.0+

**Closed by yury-s** 2022-05-18 19:55 UTC
Labels: bug
