### ISSUE TITLE
[Question] NETWORKIDLE event fired eventhough the url is not loaded completely.

### ISSUE THREAD

**Issue by Vijay757943** [microsoft/playwright-java#206] opened 2021-01-12 08:53 UTC
This works perfectly in pupeeteer . I am trying to convert the node.js code to java , so using playwright java code to automate my test case.

Have tried all below options to stop closing the browser before taking screenshot. But without fully loading the specified url it takes screenshot and closes the browser.

```
NavigateOptions navigateOptions = new NavigateOptions();
navigateOptions.withWaitUntil(LoadState.NETWORKIDLE);
page.waitForResponse(url);
WaitForSelectorOptions waitForSelectorOptions = new WaitForSelectorOptions();
waitForSelectorOptions.withState(State.VISIBLE);
page.waitForSelector("view", waitForSelectorOptions);
page.waitForSelector("react-grid-layout", waitForSelectorOptions);
page.waitForSelector("view", waitForSelectorOptions);
page.waitForSelector("dashboard-content", waitForSelectorOptions);
page.waitForSelector("react-grid-item", waitForSelectorOptions);
//Even tried to fulfil the response by 200

page.route(grafanaUrl, r -> {
				r.fulfill(new FulfillResponse().withStatus(200));
			});
page.navigate(grafanaUrl,navigateOptions);
			page.screenshot(new Page.ScreenshotOptions().withPath(Paths.get("screenshot-" + browserType.name() + ".png")));
```
	
Pupeeteer equivalent code that works - `await page.goto(rUrl, { waitUntil: 'networkidle0' });`		
Any help could be appreciated.

**Comment by yury-s** [comment] 2021-01-12 17:31
This should work as Playwright also waits for 500ms after last finished network request. Can you share the working puppeteer snippet or the page your are testing? Can you also print the network traffic
```java
    page.addListener(REQUEST, event -> {
      System.out.println("Request: " + ((Request) event.data()).url());
    });
    page.addListener(RESPONSE, event -> {
      System.out.println("Response: " + ((Response) event.data()).url());
    });
```
to ensure there are now unexpected network requests?

**Comment by Vijay757943** [comment] 2021-01-13 07:24
I have tried printing the above snippet but it is not reliable . I am not getting the reponse sysouts sometimes but i get the request sysouts always as shown in below logs.

Version used - 0.172.3
Also i am not able to provide the link since it is my local Grafana. I am able to take screenshot of Grafana with panels only sometimes as the backend code is still executing resulting in empty panels.

Tried options - Generated code via playwright-cli but not able to scroll the dashboard.

Please find below the java code and log . Also pasted the working puppeteer code .

Kindly let me know if i have to change any code snippet.

**JAVA snippet**


`               
                 
 public static void main(String[] args)  {

		       Playwright playwright = Playwright.create();
                     try {
			
                        System.out.println("Playwright---");
			String grafanaUrl = "http://localhost:3000/d/M-djRN2ik/4-test-dashboard?orgId=1";
			BrowserType browserType = 	playwright.chromium();
			LaunchOptions launchOptions = new LaunchOptions();
			launchOptions.withHeadless(true);
			launchOptions.withDevtools(false);
			//launchOptions.withEnv("DEBUG=pw:protocol");

			String auth = "user:pwd";
			byte[] encodedAuth = Base64.getEncoder().encode(auth.getBytes(StandardCharsets.ISO_8859_1));
			String authHeader = "Basic " + new String(encodedAuth);
			Map<String, String> headers = new HashMap<>();
			headers.put("Authorization", authHeader);

			Browser browser = browserType.launch(launchOptions);
			BrowserContext context = browser.newContext(
					new Browser.NewContextOptions().withViewport(1200, 800));
			Page page = context.newPage();

			page.setExtraHTTPHeaders(headers);
			page.setDefaultNavigationTimeout(120000);
			page.setViewportSize(1200, 800);

			NavigateOptions navigateOptions = new NavigateOptions();
			navigateOptions.withWaitUntil(LoadState.NETWORKIDLE);
			page.route("**", route -> {
				//System.out.println(route.request().url());
				route.continue_();
			});

                       /** hidding some css not working **/
			page.evaluate("() => { return document.getElementsByClassName('sidemenu').hidden; }");
                     /** scroll not working **/
			page.evaluate("() => window.scrollTo(0, document.body.scrollHeight)");

			page.addListener(EventType.REQUEST, e -> System.out.println("Request--"+((Request)e.data()).url()));
			page.addListener(EventType.RESPONSE, e -> System.out.println("Response--"+((Response)e.data()).url()));

			page.route("http://localhost:3000/api/datasources/proxy/**", r -> {
				r.fulfill(new FulfillResponse().withStatus(200));
			});
			page.waitForResponse(grafanaUrl);
			page.navigate(grafanaUrl,navigateOptions);
			Page.WaitForSelectorOptions waitForSelectorOptions = new Page.WaitForSelectorOptions();
			waitForSelectorOptions.withState(State.ATTACHED);
			Deferred<ElementHandle> event = page.waitForSelector(".view", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			event.get();
			Deferred<ElementHandle> revent = page.waitForSelector(".react-grid-layout", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			revent.get();
			Deferred<ElementHandle> devent = page.waitForSelector(".dashboard-content", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			devent.get();
			Deferred<ElementHandle> ievent = page.waitForSelector(".react-grid-item", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			ievent.get();
			Deferred<ElementHandle> cevent = page.waitForSelector(".panel-content", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			cevent.get();
			Deferred<ElementHandle> sevent = page.waitForSelector(".track-horizontal", new Page.WaitForSelectorOptions()
					.withState(Page.WaitForSelectorOptions.State.ATTACHED));
			sevent.get();
			page.screenshot(new Page.ScreenshotOptions().withPath(Paths.get("screenshot-" + browserType.name() + ".png")));
			PdfOptions pdfOptions =  new PdfOptions();
			pdfOptions.withPath(Paths.get("test.pdf"));
			pdfOptions.withPrintBackground(true);
			//pdfOptions.withFormat("Letter");
			//pdfOptions.withLandscape(true);
			//pdfOptions.withScale(2);
			pdfOptions.withDisplayHeaderFooter(true);
			pdfOptions.setMargin().withTop("90").withRight("10").withBottom("50").withLeft("10");
			page.pdf(pdfOptions);
			page.close();
			context.close();
			browser.close();

		} catch (Exception e) {
			e.printStackTrace();
		}finally {
			try {
				playwright.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
`

**Logs**

Failed to process descriptor at C:\Users\ADMINI~1\AppData\Local\Temp\2\playwright-java-8166996152194358923
Playwright---
2021-01-13T07:02:56.449Z pw:api navigating to "http://localhost:3000/d/M-djRN2ik/4-test-dashboard?orgId=1", waiting until "networkidle"
Request--http://localhost:3000/d/M-djRN2ik/4-test-dashboard?orgId=1
Response--http://localhost:3000/d/M-djRN2ik/4-test-dashboard?orgId=1
2021-01-13T07:02:56.497Z pw:api   navigated to "http://localhost:3000/d/M-djRN2ik/4-test-dashboard?orgId=1"
2021-01-13T07:02:57.684Z pw:api   "networkidle" event fired
2021-01-13T07:02:57.688Z pw:api waiting for selector ".view"
2021-01-13T07:02:58.638Z pw:api   "domcontentloaded" event fired
2021-01-13T07:02:58.752Z pw:api   "load" event fired
Request--http://localhost:3000/api/datasources/proxy/1
Response--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Response--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/public/fonts/fontawesome-webfont.woff2?v=4.7.0
Response--http://localhost:3000/api/datasources/proxy/1
Response--http://localhost:3000/public/fonts/fontawesome-webfont.woff2?v=4.7.0
2021-01-13T07:02:59.398Z pw:api   selector resolved to visible <div class="view">â€¦</div>
2021-01-13T07:02:59.539Z pw:api waiting for selector ".react-grid-layout"
Request--http://localhost:3000/api/datasources/proxy/1
2021-01-13T07:02:59.685Z pw:api   selector resolved to visible <div class="react-grid-layout layout">â€¦</div>
2021-01-13T07:02:59.706Z pw:api waiting for selector ".dashboard-content"
2021-01-13T07:02:59.829Z pw:api   selector resolved to visible <div class="dashboard-content">â€¦</div>
2021-01-13T07:02:59.884Z pw:api waiting for selector ".react-grid-item"
2021-01-13T07:02:59.896Z pw:api   selector resolved to visible <div id="panel-38" class="react-grid-item">â€¦</div>

_didn't receive response for the below highlighted urls_

**Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1
Request--http://localhost:3000/api/datasources/proxy/1**
2021-01-13T07:02:59.924Z pw:api waiting for selector ".panel-content"
2021-01-13T07:02:59.929Z pw:api   selector resolved to visible <div class="panel-content">â€¦</div>
2021-01-13T07:02:59.966Z pw:api waiting for selector ".track-horizontal"
2021-01-13T07:02:59.972Z pw:api   selector resolved to hidden <div class="track-horizontal">â€¦</div>

**Working puppeteer code**

`


(async () => {
   
 try {
      const browser = await puppeteer.launch({ headless: true, devtools: true, ignoreHTTPSErrors: false });
      const page = await browser.newPage();

      await page.setExtraHTTPHeaders({ 'Authorization': auth_header });

      await page.setDefaultNavigationTimeout(120000);

      await page.setViewport({
        width: width_px,
        height: 800,
        deviceScaleFactor: 2,
        isMobile: false
      })
      await page.goto(rUrl, { waitUntil: 'networkidle0' });

      await page.evaluate(() => {
        let sidemenu = document.getElementsByClassName('sidemenu');
        for (el of sidemenu) { el.hidden = true; };
      });

      var height_px = await page.evaluate(() => {
        return document.getElementsByClassName('react-grid-layout')[0].getBoundingClientRect().bottom;
      }) + 160;

      async function autoScroll(page) {
        await page.evaluate(async () => {
          await new Promise((resolve, reject) => {
            var totalHeight = 0;
            var distance = 100;
            var height_px = document.getElementsByClassName('react-grid-layout')[0].getBoundingClientRect().bottom;
            var timer = setInterval(() => {
              var scrollHeight = height_px;

              var element = document.querySelector('.view');
              element.scrollBy({
                top: distance,
                left: 0,
                behavior: 'smooth'
              });

              totalHeight += distance;

              console.log('totalHeight', totalHeight)

              if (totalHeight >= scrollHeight) {
                clearInterval(timer);
                resolve();
              }
            }, 300);
          });
        });
      }

      await autoScroll(page);

      const pdf = await page.pdf({
        //path: outfile,
        width: width_px + 'px',
        height: height_px + 'px',
        //format: 'A2', 
        scale: 1,
        displayHeaderFooter: true,
        footerTemplate: footer,
        headerTemplate: header,
        printBackground: true,
        margin: {
          top: 90,
          right: 0,
          bottom: 50,
          left: 0,
        },
      });

      await browser.close();
      res.set('Access-Control-Allow-Origin', '*');
      res.contentType("application/pdf");
      res.send(pdf);
    } catch (error) {
      console.log(error);
    }
  })()`

**Comment by yury-s** [comment] 2021-01-13 20:22
> I have tried printing the above snippet but it is not reliable . I am not getting the reponse sysouts sometimes but i get the request sysouts always as shown in below logs.

There is a chance that some of the requests fail and `NETWORKIDLE` starts counting from that point. It's not quite clear to me where 
```
_didn't receive response for the below highlighted urls_
```
comes from. Maybe there is `REQUESTFAILED` event instead of `RESPONSE` for that request?

> I have tried this code with node as well but fullscreenshot is getting trimmed and takes only the visible part.

There is a bunch of code unrelated to networkidle event. Why do you think the problem is in the networkidle event? E.g. the js snippet contains time consuming autoScroll function that is not present in the java counterpart. It'd be nice to reduce the example to just the network part as I suspect the problem might be elsewhere.

**Comment by yury-s** [comment] 2021-02-08 23:51
Closing as there was no feedback.

**Closed by yury-s** 2021-02-08 23:51 UTC
Labels: triaging

**Comment by Vijay757943** [comment] 2021-02-09 15:40
@yury-s Sorry for the delay. I was doing a lot of tries .Later tried same code(above  in pupeeteer) using Playwright in node.js . In node.js it works fine since it has async/await that makes it to wait until the entire website loads. But in Java it does not wait for NETWORK IDLE  nor a url pattern to fulfill the 200 status code. Ps this works perfectly in node pupeeteer and node playwright. 

Am I missing something or it is because of advantage due to async/await in typescript ?
