### ISSUE TITLE
Temporary Files

### ISSUE THREAD

**Issue by jschlade** [microsoft/playwright-java#1079] opened 2022-09-24 03:17 UTC
Using Playwright 1.25 for java on Windows with the Firefox driver.
Using a 1.8 JVM

Seeing lots of temp files leftover:
![temp_file_dir](https://user-images.githubusercontent.com/13022731/192077720-4ce9ab1f-3351-439a-98e3-8f1dae8928ec.JPG)

Why?
And is there a way to delete them before my Playwright application ends?

Thanks

**Comment by yury-s** [comment] 2022-09-26 18:02
Playwright Java consists of two parts: java client that provides all the APIs and a driver which is shared between all language ports. The driver is a node.js application which is archived in a maven package and is extracted into a temp directory every time you launch playwright. The directory is automatically deleted after the application finishes. You cannot delete it before you finished running playwright as it will break it.

**Comment by jschlade** [comment] 2022-09-26 18:47
Hi @yury-s  - This is a bug then as I don't see this getting cleaned up. Is there a way to debug this? Thanks

**Comment by yury-s** [comment] 2022-09-26 20:28
The files/dirs are marked as [deleteOnExit()](https://github.com/microsoft/playwright-java/blob/ae54a7da554b9328c16d6bcb17db93c5e57342a6/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L44) so if JVM exits without errors the should be removed.

**Comment by jschlade** [comment] 2022-09-26 22:44
They aren't. I have a long running program that's doing multiple searches over many hours and I see left over files like this so for some reason playwright didn't delete the dir containing the node.exe file when it started at 8:13 am and I exited in around 2:30 pm today.

@yury-s  - Please help me debug this. Why is this happening?

Thanks

![image](https://user-images.githubusercontent.com/13022731/192393289-43a9cb0d-4ddd-4e8f-a147-36119a933bae.png)

**Comment by yury-s** [comment] 2022-09-27 15:49
It may happen if node.exe didn't exit properly and still holding some of the files. Can you check for remaining node processes after the app exits? Usually Playwright will kill them before exit if the are not responsive but maybe there is a bug.

**Comment by jschlade** [comment] 2022-09-27 15:57
I don't see that node.exe is still running?
But I see this message all the time:

INFO: Closing client connection.
**The batch file cannot be found.**

- What batch file is it looking for?
- Is this doing the deleting?
- Any other debugging I can enable?

![image](https://user-images.githubusercontent.com/13022731/192575761-7539fdd6-cad3-4db9-b477-13a9060b04b1.png)

Thanks

**Comment by yury-s** [comment] 2022-09-27 16:06
> > INFO: Closing client connection.
> > **The batch file cannot be found.**
> 
> This may be printed if the batch file that we use to launch node is missing, e.g. it was deleted from the temp directory already.

[This](https://github.com/microsoft/playwright-java/blob/ae54a7da554b9328c16d6bcb17db93c5e57342a6/driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java#L69-L70) is where we construct the file name. You can pause in the debugger there, and check if `playwright.cmd` is actually present at that path.

**Comment by jschlade** [comment] 2022-09-27 17:48
INFO: Closing client connection.
2022-09-27T17:42:33.165Z pw:browser [pid=28088] <gracefully close start>
2022-09-27T17:42:33.465Z pw:browser [pid=28088] <process did exit: exitCode=0, signal=null>
2022-09-27T17:42:33.466Z pw:browser [pid=28088] starting temporary directories cleanup
2022-09-27T17:42:33.500Z pw:browser [pid=28088] finished temporary directories cleanup
2022-09-27T17:42:33.500Z pw:browser [pid=28088] <gracefully close end>
The batch file cannot be found.

![image](https://user-images.githubusercontent.com/13022731/192599205-a8599e22-508d-4311-8b96-052915f5e6c3.png)

Still seeing leftover directories:

- mozilla-temp-files has nothing in it.
- playwright-java-7998165960572586948 has node.exe in it.

Thanks

**Comment by yury-s** [comment] 2022-09-27 18:09
> * mozilla-temp-files has nothing in it.

This might be created by firefox, playwright itself doesn't create such folder as far as I know.

> * playwright-java-7998165960572586948 has node.exe in it.

It means that the node process is still hanging around preventing the directory from being deleted. You should be able to find it in the task manager.

> The batch file cannot be found.

I cannot make sense of it, it looks like you are trying to launch playwright again after the cleanup started. Can it be that there is a periodic job that does temp folder cleanup and interferes with the running Playwright instance?

**Comment by jschlade** [comment] 2022-09-27 18:45
Okay so there it is running:

![image](https://user-images.githubusercontent.com/13022731/192606618-7cd2ad28-0e55-42b3-a65a-7fcdd8fb64c7.png)

I see this:

2022-09-27T18:20:39.625Z pw:install created DriverJar: C:\Users\xxxx\AppData\Local\Temp\playwright-java-7557468934805508290
2022-09-27T18:20:39.627Z pw:install initializing driver
2022-09-27T18:20:40.068Z pw:install extracted driver from jar to C:\Users\xxxx\AppData\Local\Temp\playwright-java-7557468934805508290\playwright.cmd
2022-09-27T18:20:41.750Z pw:install Chromium 105.0.5195.19 (playwright build v1019) is already downloaded.
2022-09-27T18:20:41.750Z pw:install FFMPEG playwright build v1007 is already downloaded.
2022-09-27T18:20:41.751Z pw:install Firefox 103.0 (playwright build v1344) is already downloaded.
2022-09-27T18:20:41.751Z pw:install Webkit 16.0 (playwright build v1699) is already downloaded.
2022-09-27T18:20:41.760Z pw:install driver initialized.
2022-09-27T18:20:42.212Z pw:browser <launching> C:\Users\xxxx\AppData\Local\ms-playwright\firefox-1344\firefox\firefox.exe -no-remote -headless -profile C:\Users\xxxxx\AppData\Local\Temp\playwright_firefoxdev_profile-bFSqGD -juggler-pipe -silent
2022-09-27T18:20:42.214Z pw:browser <launched> pid=8080
2022-09-27T18:20:42.245Z pw:browser [pid=8080][err] *** You are running in headless mode.
2022-09-27T18:20:42.495Z pw:browser [pid=8080][out] 
2022-09-27T18:20:42.495Z pw:browser [pid=8080][out] Juggler listening to the pipe


Then when I quit my application:

INFO: Closing client connection.
2022-09-27T18:33:06.975Z pw:browser [pid=8080] <gracefully close start>
2022-09-27T18:33:07.103Z pw:browser [pid=8080] <process did exit: exitCode=0, signal=null>
2022-09-27T18:33:07.103Z pw:browser [pid=8080] starting temporary directories cleanup
2022-09-27T18:33:07.139Z pw:browser [pid=8080] finished temporary directories cleanup
2022-09-27T18:33:07.139Z pw:browser [pid=8080] <gracefully close end>
The batch file cannot be found.

No node.exe:

![image](https://user-images.githubusercontent.com/13022731/192608684-5a939508-e3f3-4323-b2aa-71860edce571.png)

And the folder is still there:

![image](https://user-images.githubusercontent.com/13022731/192609108-e3698149-b681-4a5b-b61d-9ba0bd193d8e.png)

There isn't anything deleting directories, etc. from my %temp% directory.
Why is it trying to run this .cmd file when the program is exiting after the cleanup? That doesn't make sense.

**Comment by yury-s** [comment] 2022-09-27 20:24
> Why is it trying to run this .cmd file when the program is exiting after the cleanup? That doesn't make sense.

I have no explanation for that, it should not. Perhaps it's the same code that prints "INFO: Closing client connection." (Playwright doesn't have such messages). Would you be able to share minimal reproducible example?

**Comment by jschlade** [comment] 2022-09-27 20:43
INFO: Closing client connection. - Is my code.
My app logs into a financial website so I'm not sure it would be easy to reduce it into something non proprietary.

Based on what I've seen it seems like there are a few issues here. Can you give me another build that has more debugging capabilities?

Thanks

**Comment by yury-s** [comment] 2022-09-27 22:10
> Based on what I've seen it seems like there are a few issues here. Can you give me another build that has more debugging capabilities?

I could but I'm not sure where to put that logging. It seems that the problem is somewhere in the implementation of the `deleteOnExit()` method + how the node instances are shutdown. Can you check if it's reproducible it with a simple example, like one of those we have [in the examples](https://github.com/microsoft/playwright-java/tree/main/examples) directory?

**Comment by yury-s** [comment] 2022-10-05 23:12
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Closed by yury-s** 2022-10-05 23:12 UTC

**Comment by 89ppliszka** [comment] 2024-02-20 20:46
Hey. I'm seeing the same issue with temp files. 'The batch file cannot be found.'
Playwright version: 1.36.0
Java: 21
![image](https://github.com/microsoft/playwright-java/assets/62641395/1cb4cd0a-b9b8-492c-b6d0-65bc0bf4d3f0)
I'm closing the context first, then the browser.
Is there a solution for this?

**Comment by NIKOLENKO-TE** [comment] 2024-03-12 22:39
**`The batch file cannot be found.`**
Same problem. I tried different versions of everything possible.
I created the simplest test project. After every test I see this error.
After each test, the temporary folder is not deleted. The file `node.exe` remains in it.
The `playwright.cmd` file remains if the test is interrupted. Does this error occur because the `node.exe` process is still busy when the test completes and it cannot delete the temporary folder?
`Gradle:` **8.4, 8.5, 8.6**;
`Playwright:` **1.41.2**;
`Java:` **11, 17, 18, 21**;
I added my own variable Windows but it didn't help.

![Screenshot 2024-03-12 230904](https://github.com/microsoft/playwright-java/assets/133020063/7faf6288-9f33-4d8d-88b8-094fe467a61e)
![Screenshot 2024-03-12 231039](https://github.com/microsoft/playwright-java/assets/133020063/580013a7-55af-46a6-be75-07359bf2e2eb)
![Screenshot 2024-03-12 231131](https://github.com/microsoft/playwright-java/assets/133020063/f12b7b59-79eb-40ff-a2cc-270a5609c3e2)
![Screenshot 2024-03-12 231345](https://github.com/microsoft/playwright-java/assets/133020063/d34f89ed-f398-4c77-85d8-3d4ddf9c5164)
![Screenshot 2024-03-12 231841](https://github.com/microsoft/playwright-java/assets/133020063/157567c8-0c02-46fc-bd2d-5cf492b673ed)
![Screenshot 2024-03-12 232351](https://github.com/microsoft/playwright-java/assets/133020063/0a1552be-4986-402e-ba88-71628df61e7c)
![Screenshot 2024-03-12 233837](https://github.com/microsoft/playwright-java/assets/133020063/a678d31a-c9b8-4547-9a95-d314295d742d)

**Comment by rojashr** [comment] 2024-04-16 14:59
Hello @yury-s I hope you are well, is there a reason this issue was closed? 

I can reproduce this consistently on my local setup and in a remote server, I am using Java 11 and 17 and Playwright version 1.37.0.

The description provided by @NIKOLENKO-TE above is quite thorough about the problem, do you need more information from our side?
